[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/fuzxxl/freefare"
  version = "0.3.0"

[[constraint]]
  name = "github.com/fuzxxl/nfc"
  version = "2.0.2"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.1.0"

[[constraint]]
  name = "github.com/labstack/gommon"
  version = "0.2.8"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"
